# Generated by Django 3.2.25 on 2024-07-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_citrus', models.BooleanField(verbose_name='is citrus')),
                ('expires_on', models.DateField(verbose_name='expires on')),
            ],
            options={
                'verbose_name': 'fruit',
                'verbose_name_plural': 'fruits',
            },
        ),
    ]
