name: Main

on:
  push:
  pull_request:
  issues:
  issue_comment:
  workflow_dispatch:

jobs:
  main:
    uses: ocadotechnology/codeforlife-workspace/.github/workflows/backend.yaml@main
    secrets: inherit
